-- =========================================
-- PostgreSQL DDL по ER-диаграмме
-- =========================================

-- На случай повторного запуска
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS cell_coordinates CASCADE;
DROP TABLE IF EXISTS formula_elements CASCADE;
DROP TABLE IF EXISTS axis_elements CASCADE;
DROP TABLE IF EXISTS axis_element_dictionary CASCADE;
DROP TABLE IF EXISTS axis_element_types CASCADE;
DROP TABLE IF EXISTS cells CASCADE;
DROP TABLE IF EXISTS cell_types CASCADE;
DROP TABLE IF EXISTS axes CASCADE;
DROP TABLE IF EXISTS meta_table CASCADE;
DROP TABLE IF EXISTS unit_dictionary CASCADE;
DROP TABLE IF EXISTS work_dictionary CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- =========================================
-- Справочники и базовые таблицы
-- =========================================

BEGIN;

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE roles (
    id_role BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE unit_categories (
    id_unit_category BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE axis_element_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

CREATE TABLE cell_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

CREATE TABLE axis_element_dictionary (
    id_category_element BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT,
    parent_id BIGINT,
    element_code TEXT,
    CONSTRAINT fk_axis_element_dictionary_parent
        FOREIGN KEY (parent_id)
        REFERENCES axis_element_dictionary (id_category_element)
        ON DELETE SET NULL
);

CREATE TABLE work_dictionary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    value TEXT,
    parent_id BIGINT,
    element_code TEXT,
    CONSTRAINT fk_work_dictionary_parent
        FOREIGN KEY (parent_id)
        REFERENCES work_dictionary (id)
        ON DELETE SET NULL
);

CREATE TABLE unit_dictionary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name TEXT,
    abbreviation TEXT,
    id_unit_category BIGINT,
    CONSTRAINT fk_unit_dictionary_unit_category
        FOREIGN KEY (id_unit_category)
        REFERENCES unit_categories (id_unit_category)
        ON DELETE SET NULL
);

CREATE TABLE users (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    middle_name TEXT,
    login TEXT,
    password TEXT,
    password_hash TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    id_department BIGINT,
    CONSTRAINT fk_users_department
        FOREIGN KEY (id_department)
        REFERENCES departments (id)
        ON DELETE SET NULL
);

CREATE TABLE meta_table (
    id_meta_table BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    id_unit BIGINT,
    id_work BIGINT,
    id_user BIGINT,
    CONSTRAINT fk_meta_table_unit
        FOREIGN KEY (id_unit)
        REFERENCES unit_dictionary (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_meta_table_work
        FOREIGN KEY (id_work)
        REFERENCES work_dictionary (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_meta_table_user
        FOREIGN KEY (id_user)
        REFERENCES users (id_user)
        ON DELETE SET NULL
);

CREATE TABLE axes (
    id_axe BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_meta_table BIGINT,
    axis_name TEXT,
    axis_order INTEGER,
    axis_position INTEGER,
    CONSTRAINT fk_axes_meta_table
        FOREIGN KEY (id_meta_table)
        REFERENCES meta_table (id_meta_table)
        ON DELETE CASCADE
);

CREATE TABLE axis_elements (
    id_axes_element BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_axe BIGINT,
    value TEXT,
    id_category_elem BIGINT,
    id_axis_element_type BIGINT,
    CONSTRAINT fk_axis_elements_axe
        FOREIGN KEY (id_axe)
        REFERENCES axes (id_axe)
        ON DELETE CASCADE,
    CONSTRAINT fk_axis_elements_category_elem
        FOREIGN KEY (id_category_elem)
        REFERENCES axis_element_dictionary (id_category_element)
        ON DELETE SET NULL,
    CONSTRAINT fk_axis_elements_type
        FOREIGN KEY (id_axis_element_type)
        REFERENCES axis_element_types (id)
        ON DELETE SET NULL
);

CREATE TABLE cells (
    id_cell BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cell_type BIGINT,
    value TEXT,
    CONSTRAINT fk_cells_cell_type
        FOREIGN KEY (id_cell_type)
        REFERENCES cell_types (id)
        ON DELETE SET NULL
);

CREATE TABLE cell_coordinates (
    id_axes_element BIGINT,
    id_cell BIGINT,
    CONSTRAINT fk_cell_coordinates_axis_element
        FOREIGN KEY (id_axes_element)
        REFERENCES axis_elements (id_axes_element)
        ON DELETE CASCADE,
    CONSTRAINT fk_cell_coordinates_cell
        FOREIGN KEY (id_cell)
        REFERENCES cells (id_cell)
        ON DELETE CASCADE
);

CREATE TABLE formula_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_meta_table BIGINT,
    referenced_object_id BIGINT,
    formula_element_type TEXT,
    formula_element TEXT,
    formula_element_description TEXT,
    id_unit BIGINT,
    CONSTRAINT fk_formula_elements_meta_table
        FOREIGN KEY (id_meta_table)
        REFERENCES meta_table (id_meta_table)
        ON DELETE CASCADE,
    CONSTRAINT fk_formula_elements_unit
        FOREIGN KEY (id_unit)
        REFERENCES unit_dictionary (id)
        ON DELETE SET NULL
);

CREATE TABLE user_roles (
    id_role BIGINT,
    id_user BIGINT,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (id_role)
        REFERENCES roles (id_role)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (id_user)
        REFERENCES users (id_user)
        ON DELETE CASCADE
);

CREATE INDEX idx_axis_element_dictionary_parent_id
    ON axis_element_dictionary (parent_id);

CREATE INDEX idx_work_dictionary_parent_id
    ON work_dictionary (parent_id);

CREATE INDEX idx_unit_dictionary_id_unit_category
    ON unit_dictionary (id_unit_category);

CREATE INDEX idx_users_id_department
    ON users (id_department);

CREATE INDEX idx_meta_table_id_unit
    ON meta_table (id_unit);

CREATE INDEX idx_meta_table_id_work
    ON meta_table (id_work);

CREATE INDEX idx_meta_table_id_user
    ON meta_table (id_user);

CREATE INDEX idx_axes_id_meta_table
    ON axes (id_meta_table);

CREATE INDEX idx_axis_elements_id_axe
    ON axis_elements (id_axe);

CREATE INDEX idx_axis_elements_id_category_elem
    ON axis_elements (id_category_elem);

CREATE INDEX idx_axis_elements_id_axis_element_type
    ON axis_elements (id_axis_element_type);

CREATE INDEX idx_cells_id_cell_type
    ON cells (id_cell_type);

CREATE INDEX idx_cell_coordinates_id_axes_element
    ON cell_coordinates (id_axes_element);

CREATE INDEX idx_cell_coordinates_id_cell
    ON cell_coordinates (id_cell);

CREATE INDEX idx_formula_elements_id_meta_table
    ON formula_elements (id_meta_table);

CREATE INDEX idx_formula_elements_id_unit
    ON formula_elements (id_unit);

CREATE INDEX idx_user_roles_id_role
    ON user_roles (id_role);

CREATE INDEX idx_user_roles_id_user
    ON user_roles (id_user);

COMMIT;