CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE roles (
    id_role BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

CREATE TABLE users (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    middle_name TEXT,
    login TEXT,
    password TEXT,
    password_hash TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    id_department BIGINT,
    CONSTRAINT fk_users_department
        FOREIGN KEY (id_department)
        REFERENCES departments (id)
        ON DELETE SET NULL
);

CREATE TABLE user_roles (
    id_role BIGINT,
    id_user BIGINT,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (id_role)
        REFERENCES roles (id_role)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (id_user)
        REFERENCES users (id_user)
        ON DELETE CASCADE
);







-- Вставка данных о цехах (departments)
INSERT INTO departments (name)
VALUES
    ('Цех 1'),
    ('Цех 2'),
    ('Цех 3'),
    ('Цех 4');

-- Вставка данных о ролях
INSERT INTO roles (name)
VALUES
    ('администратор'),
    ('эксперт'),
    ('нормировщик');

-- Вставка данных о пользователях (users)
INSERT INTO users (first_name, last_name, middle_name, login, password, password_hash, created_at, updated_at, id_department)
VALUES
    ('Иван', 'Иванов', 'Иванович', 'admin_user', 'password123', 'hashed_password_1', NOW(), NOW(), 1),  -- администратор
    ('Петр', 'Петров', 'Петрович', 'expert_user', 'password123', 'hashed_password_2', NOW(), NOW(), 2), -- эксперт
    ('Сергей', 'Сергеев', 'Сергеевич', 'normirovshik_user', 'password123', 'hashed_password_3', NOW(), NOW(), 3); -- нормировщик

-- Вставка связей пользователей и ролей (user_roles)
-- Администратор имеет несколько ролей
INSERT INTO user_roles (id_role, id_user)
VALUES
    ((SELECT id_role FROM roles WHERE name = 'администратор'), (SELECT id_user FROM users WHERE login = 'admin_user')),  -- роль администратора
    ((SELECT id_role FROM roles WHERE name = 'эксперт'), (SELECT id_user FROM users WHERE login = 'admin_user')),        -- роль эксперта
    ((SELECT id_role FROM roles WHERE name = 'нормировщик'), (SELECT id_user FROM users WHERE login = 'admin_user')),    -- роль нормировщика
    ((SELECT id_role FROM roles WHERE name = 'эксперт'), (SELECT id_user FROM users WHERE login = 'expert_user')),       -- эксперт
    ((SELECT id_role FROM roles WHERE name = 'нормировщик'), (SELECT id_user FROM users WHERE login = 'normirovshik_user')); -- нормировщик